### ISSUE TITLE
Rename to swift4-module-template

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/swift4-module-template#39]
Rename this project to swift4-module template. The new Xcode just hit Gold Master so it is GO time.

Alternatives considered: 
 * Make a new project -- this is stupid because nobody wants to make new swift3 projects once Xcode 9 is out. AND because this project is only about making NEW projects.

Work plan:
 - [x] Rename the project
 - [x] Update the REMOTES on my computer
 - [x] Ask people linking to the old project to now link to the new one
 - [x] s/oldurl/newurl/g in the GitHub

---

Old links, care of AHREFS:

* Reach out to them to offer updated link to this project.

- [x] http://cocoadocs.org/docsets/FDWaveformView/2.2.1/
- [x] http://cocoadocs.org/docsets/FDWaveformView/2.2.1/index.html
- [x] http://cocoadocs.org/docsets/SwiftVer/1.0.1/
- [x] http://cocoadocs.org/docsets/ZHTableViewGroupSwift/0.2.0/
- [x] http://cocoadocs.org/docsets/ZHTableViewGroupSwift/0.2.0/index.html
- [x] http://cocoapods.org/pods/FDWaveformView
- [x] http://cocoapods.org/pods/ZHTableViewGroupSwift
- [x] http://getawesomeness.herokuapp.com/get/swift
- [x] http://hnpaper.forge.partlab.io/u/fulldecent
- [x] http://uiview.com/project/93/
- [x] http://www.alexruperez.com/entries/2014-matteocrippa-awesome-swift
- [x] http://www.alexruperez.com/repos/71-awesome-swift
- [x] https://cocoapods.org/pods/FDWaveformView
- [x] https://cocoapods.org/pods/ZHTableViewGroupSwift
- [x] https://devhub.io/repos/SwiftCarlos-awesome-swift
- [x] https://devhub.io/repos/candostdagdeviren-awesome-swift
- [x] https://devhub.io/repos/fulldecent-swift3-module-template
- [x] https://devhub.io/repos/jonkykong-awesome-swift
- [x] https://devhub.io/repos/malcommac-awesome-swift
- [x] https://devhub.io/repos/matteocrippa-awesome-swift
- [x] https://devhub.io/repos/omaralbeik-awesome-swift
- [x] https://devhub.io/repos/rchatham-awesome-swift
- [x] https://devhub.io/repos/ytakzk-awesome-swift
- [x] https://devhub.io/zh/repos/SwiftCarlos-awesome-swift
- [x] https://devhub.io/zh/repos/candostdagdeviren-awesome-swift
- [x] https://devhub.io/zh/repos/jonkykong-awesome-swift
- [x] https://devhub.io/zh/repos/malcommac-awesome-swift
- [x] https://devhub.io/zh/repos/matteocrippa-awesome-swift
- [x] https://devhub.io/zh/repos/omaralbeik-awesome-swift
- [x] https://devhub.io/zh/repos/rchatham-awesome-swift
- [x] https://devhub.io/zh/repos/ytakzk-awesome-swift
- [x] https://getawesomeness.herokuapp.com/get/swift
- [x] https://github.oldjpg.com/repository/47279041
- [x] https://libraries.io/github/fulldecent/swift3-module-template
- [x] https://libraries.io/github/pavangandhi/SwiftNew
- [x] https://news.ycombinator.com/item?id=12515713
- [x] https://porter.io/daily/2016-09-16/
- [x] https://porter.io/github.com/fulldecent/swift3-module-template
- [x] https://porter.io/github.com/matteocrippa/awesome-swift
- [x] https://project-awesome.org/matteocrippa/awesome-swift
- [x] https://recordnotfound.com/awesome-swift-marmelroy-89681
- [x] https://recordnotfound.com/awesome-swift-matteocrippa-1387
- [x] https://recordnotfound.com/swift3-module-template-fulldecent-137320
- [x] https://swift.zeef.com/robin.eggenkamp

**Comment by wtrocki** [comment]
See: https://github.com/fulldecent/swift4-module-template/pull/41

**Comment by fulldecent** [comment]
Thank you. Updated this issue to address inbound links that can be fixed.
